force-app/main/default/objects/OP_Teilnehmer__c/OP_Teilnehmer__c.object-meta.xml
<CustomObject>
    <label>Kostenverteilung</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Kostenverteilungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OP_Teilnehmer__c/fields/Istkosten_Gesamt__c.field-meta.xml
<CustomField>
    <fullName>Istkosten_Gesamt__c</fullName>
    <formula>Anteilige_Istkosten__c +  Individuelle_Istkosten__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Istkosten Gesamt</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OP_Teilnehmer__c/fields/Organisationspunkt__c.field-meta.xml
<CustomField>
    <fullName>Organisationspunkt__c</fullName>
    <label>Organisationspunkt</label>
    <referenceTo>Organisationspunkt__c</referenceTo>
    <relationshipName>OP_Teilnehmer</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OP_Teilnehmer__c/fields/Teilnehmer__c.field-meta.xml
<CustomField>
    <fullName>Teilnehmer__c</fullName>
    <label>Teilnehmer</label>
    <referenceTo>Teilnehmer__c</referenceTo>
    <relationshipName>OP_Teilnehmer</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Organisationspunkt__c/Organisationspunkt__c.object-meta.xml
<CustomObject>
    <label>Organisationspunkt</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organisationspunkte</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Organisationspunkt__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&#39;Planung&#39;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planung</fullName>
                <default>true</default>
                <label>Planung</label>
            </value>
            <value>
                <fullName>In Arbeit</fullName>
            </value>
            <value>
                <fullName>Abgeschlossen</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Teilnehmer__c/Teilnehmer__c.object-meta.xml
<CustomObject>
    <label>Teilnehmer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teilnehmer</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Teilnehmer__c/fields/Anzahlungsbetrag__c.field-meta.xml
<CustomField>
    <fullName>Anzahlungsbetrag__c</fullName>
    <label>Anzahlungsbetrag</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Teilnehmer__c/fields/Istkosten_Gesamt__c.field-meta.xml
<CustomField>
    <fullName>Istkosten_Gesamt__c</fullName>
    <label>Istkosten Gesamt</label>
    <summarizedField>OP_Teilnehmer__c.Istkosten_Gesamt__c</summarizedField>
    <summaryForeignKey>OP_Teilnehmer__c.Teilnehmer__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Teilnehmer__c/fields/Saldo__c.field-meta.xml
<CustomField>
    <fullName>Saldo__c</fullName>
    <formula>Istkosten_Gesamt__c -  Zahlungen_Gesamt__c +  Vorschuss_gesamt__c - Anzahlungsbetrag__c +  Rueckzahlbetrag__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Saldo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Teilnehmer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&#39;Interesse&#39;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Interesse</fullName>
                <default>true</default>
                <label>Interesse</label>
            </value>
            <value>
                <fullName>Bestätigt</fullName>
            </value>
            <value>
                <fullName>Bezahlt</fullName>
            </value>
            <value>
                <fullName>Teilgenommen</fullName>
            </value>
            <value>
                <fullName>Rückzahlung</fullName>
            </value>
            <value>
                <fullName>Sonstig</fullName>
            </value>
            <value>
                <fullName>Offen</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Teilnehmer__c/fields/Vorschuss_gesamt__c.field-meta.xml
<CustomField>
    <fullName>Vorschuss_gesamt__c</fullName>
    <label>Vorschuss gesamt</label>
    <summarizedField>Zahlung__c.Vorschuss__c</summarizedField>
    <summaryForeignKey>Zahlung__c.Teilnehmer__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Teilnehmer__c/fields/Zahlungen_Gesamt__c.field-meta.xml
<CustomField>
    <fullName>Zahlungen_Gesamt__c</fullName>
    <label>Zahlungen Gesamt</label>
    <summarizedField>Zahlung__c.Zahlbetrag__c</summarizedField>
    <summaryForeignKey>Zahlung__c.Teilnehmer__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Zahlung__c/Zahlung__c.object-meta.xml
<CustomObject>
    <label>Zahlung</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zahlungen</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Zahlung__c/fields/Organisationspunkt__c.field-meta.xml
<CustomField>
    <fullName>Organisationspunkt__c</fullName>
    <label>Organisationspunkt</label>
    <referenceTo>Organisationspunkt__c</referenceTo>
    <relationshipLabel>Zahlungen</relationshipLabel>
    <relationshipName>Zahlung</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Zahlung__c/fields/Teilnehmer__c.field-meta.xml
<CustomField>
    <fullName>Teilnehmer__c</fullName>
    <label>Teilnehmer</label>
    <referenceTo>Teilnehmer__c</referenceTo>
    <relationshipName>Z_Teilnehmer</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Zahlung__c/fields/Vorschuss__c.field-meta.xml
<CustomField>
    <fullName>Vorschuss__c</fullName>
    <label>Vorschuss</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zahlung__c/fields/Zahlbetrag__c.field-meta.xml
<CustomField>
    <fullName>Zahlbetrag__c</fullName>
    <label>Zahlbetrag</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CTRL_Report.cls
Public with sharing class CTRL_Report
{
    public list<Teilnehmer__c> lTN {get;set;}
    public map<String,list<OP_Teilnehmer__c>> mCost {get;set;}
    public map<String,list<Zahlung__c>> mPay {get;set;}
    
    /*public class cReport
    {
        public Teilnehmer__c oTN {get;set;}
        public list<OP_Teilnehmer__c> lCost {get;set;}
        public list<Zahlung__c> lPay {get;set;}    
        public cReport()
        {
        }
    }
    
    public list<cReport> lReport {get;set;}
    */
  
    public CTRL_Report()
    {
        mCost = new map<String,list<OP_Teilnehmer__c>>();
        mPay = new map<String,list<Zahlung__c>>();
        lTN = [select Id, Name, Anzahlungsbetrag__c, Istkosten_Gesamt__c, Zahlungen_Gesamt__c, Vorschuss_gesamt__c, Saldo__c 
                                          from Teilnehmer__c 
                                          where Status__c = 'Bezahlt'
                                          order by Name];
        for (Teilnehmer__c oTN:lTN)
        {
            mCost.put(oTN.Id, new list<OP_Teilnehmer__c>()); 
            mPay.put(oTN.Id, new list<Zahlung__c>());     
        }
                                          
                                          
        for (OP_Teilnehmer__c oCost : [Select Id, Organisationspunkt__r.Name, Istkosten_Gesamt__c, Teilnehmer__c from OP_Teilnehmer__c order by Teilnehmer__c , Organisationspunkt__r.Name])
        {
            list<OP_Teilnehmer__c> lTemp = new list<OP_Teilnehmer__c>();
            if (mCost.get(oCost.Teilnehmer__c) != null)
            {
                lTemp = mCost.get(oCost.Teilnehmer__c);
            }
            lTemp.add(oCost);
            mCost.put(oCost.Teilnehmer__c,lTemp);
        }
        
        
        
        for (Zahlung__c oPay : [Select Id, Organisationspunkt__r.Name, Zahlbetrag__c, Vorschuss__c, Teilnehmer__c from Zahlung__c order by Teilnehmer__c , Organisationspunkt__r.Name])
        {
            list<Zahlung__c> lTemp = new list<Zahlung__c>();
            if (mPay.get(oPay.Teilnehmer__c) != null)
            {
                lTemp = mPay.get(oPay.Teilnehmer__c);
            }
            lTemp.add(oPay);
            mPay.put(oPay.Teilnehmer__c,lTemp);
        }       
    }
}