force-app/main/default/objects/Reise__c/Reise__c.object-meta.xml
<CustomObject>
    <label>Reise</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reisen</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reise__c/fields/Ende__c.field-meta.xml
<CustomField>
    <fullName>Ende__c</fullName>
    <label>Ende</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reise__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Registration</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Teilnehmer__c/Teilnehmer__c.object-meta.xml
<CustomObject>
    <label>Teilnehmer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teilnehmer</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Teilnehmer__c/fields/Reise__c.field-meta.xml
<CustomField>
    <fullName>Reise__c</fullName>
    <label>Reise</label>
    <referenceTo>Reise__c</referenceTo>
    <relationshipLabel>Teilnehmer</relationshipLabel>
    <relationshipName>Teilnehmer</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CTRL_Tristars_Register.cls
Public with sharing class CTRL_Tristars_Register
{
    public Reise__c oReise {get;set;}
    public Teilnehmer__c oTN {get;set;}
    public String sMessage {get;set;}
  
  
    //Constructor
    public CTRL_Tristars_Register ()
    {
        list<Reise__c> lR = [Select Id, Name, Start__c, Ende__c from Reise__c where Registration__c = true];
        if (lR!= null && lR.size() > 0)
        {
            oReise = lR[0];
            oTN = new Teilnehmer__c();
            oTN.Reise__c = oReise.Id;
            sMessage = '';
        }else
        {
            sMessage = 'Keine Reise zur Registrierung gefunden.';
        }  
    }
    
    
    public pagereference noNew()
    {
        oTN = new Teilnehmer__c();
        oTN.Reise__c = oReise.Id;
        return null;
    }
    
    public pagereference doSave()
    {
        try
        {
            insert oTN;
            sMessage = 'Teilnehmer registriert';
        }catch(exception e)
        {
            sMessage = e.getmessage();
        }
        return null;
    }
    
    
    public pagereference doCancel()
    {
        return null;
        
    }
}