force-app/main/default/objects/Reise__c/Reise__c.object-meta.xml
<CustomObject>
    <label>Reise</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reisen</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reise__c/fields/Aktiv__c.field-meta.xml
<CustomField>
    <fullName>Aktiv__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Aktiv</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reise__c/fields/Ende__c.field-meta.xml
<CustomField>
    <fullName>Ende__c</fullName>
    <label>Ende</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Teilnehmer__c/Teilnehmer__c.object-meta.xml
<CustomObject>
    <label>Teilnehmer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teilnehmer</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Teilnehmer__c/fields/Reise__c.field-meta.xml
<CustomField>
    <fullName>Reise__c</fullName>
    <label>Reise</label>
    <referenceTo>Reise__c</referenceTo>
    <relationshipLabel>Teilnehmer</relationshipLabel>
    <relationshipName>Teilnehmer</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Teilnehmer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&#39;Interesse&#39;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Interesse</fullName>
                <default>true</default>
                <label>Interesse</label>
            </value>
            <value>
                <fullName>Bestätigt</fullName>
            </value>
            <value>
                <fullName>Bezahlt</fullName>
            </value>
            <value>
                <fullName>Teilgenommen</fullName>
            </value>
            <value>
                <fullName>Rückzahlung</fullName>
            </value>
            <value>
                <fullName>Sonstig</fullName>
            </value>
            <value>
                <fullName>Offen</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CTRL_Site.cls
public class CTRL_Site 
{
    public Reise__c oReise {get;set;}
    public list<selectoption> lSO {get;set;}
    public String sFilter {get;set;}

    
    public CTRL_Site () 
    {
        oReise = [Select Id, name, start__c, ende__c from Reise__c where Aktiv__c = true limit 1];
        lSO = new list<SelectOption>();
        lSO.add(new SelectOption('Bezahlt', 'Bezahlt'));
        //lSO.add(new SelectOption('Bestätigt', 'Bestätigt'));
        //lSO.add(new SelectOption('Interesse', 'Interesse - noch nicht bestätigt'));
        //lSO.add(new SelectOption('Offen', 'Offen'));
        //lSO.add(new SelectOption('Sonstig', 'Sonstig - z.B. Organisator'));        
        sFilter = 'Bezahlt';
    }

    public pagereference refresh()
    {
        
        return null;
    }
    
    public list<Teilnehmer__c> getTeilnehmer()
    {
        String sSOQL = 'Select id, Name, STatus__c from Teilnehmer__c where Reise__c = \'' + oReise.Id + '\'';
        sSOQL = sSOQL + ' AND Status__c = \'' + sFilter + '\' ';
        system.debug('**************sSOQL: ' + sSOQL);
        sSOQL = sSOQL + ' Order By Name';
        
        list<Teilnehmer__c> lTN = database.query(sSOQL);
        return lTN;
    }

    
       
}